const  obj = [
    {
      id:1,
      title: "IRON MAN 1",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmqZpxuTwy7Zh5JqkqTtWFmzv_obEFTtyuvA",
      view: "20M",
      channel: "Ranjeet Tech",
      time: "1 Year Ago",
      bg: "red",
      verified: true,
    },
    {
      id:2,
      title: "IRON MAN 2",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfanzqofntQ2gU3iR7yvkamngm4gmdVUwJ6g",
      view: "999k",
      channel: "Ranjeet Tech",
      time: "3 Year Ago",
      bg: "green",
      verified: false,
    },
    {
      id:3,
      title: "IRON MAN 3",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmqZpxuTwy7Zh5JqkqTtWFmzv_obEFTtyuvA",
      view: "20M",
      channel: "Ranjeet Tech",
      time: "1 Month Ago",
      bg: "blue",
      verified: true,
    },
    {
      id:4,
      title: "IRON MAN 5",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfanzqofntQ2gU3iR7yvkamngm4gmdVUwJ6g",
      view: "999k",
      channel: "Ranjeet Tech",
      time: "6 Year Ago",
      bg: "green",
      verified: false,
    },
    {
      id:5,
      title: "IRON MAN 6",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmqZpxuTwy7Zh5JqkqTtWFmzv_obEFTtyuvA",
      view: "20M",
      channel: "Ranjeet Tech",
      time: "4 Year Ago",
      bg: "blue",
      verified: true,
    },
    
  ];

  export default obj;